name: trefide_devel
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy=1.19
  - mkl-devel=2021.4
  - cython
  - scikit-learn
  - jupyter
  - matplotlib
  - h5py
  - pip
  - pip:
      - tifffile==2023.4.12
      - opencv-python
